DROP TABLE IF EXISTS candidate;

CREATE TABLE candidate (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  party TEXT NOT NULL,
  birth_year YEAR NOT NULL,
  winning BOOLEAN NOT NULL
);
